package main.ast.nodes.expression.operator;

public enum BinaryOperator {
    EQUAL, NOT_EQUAL,GREATER_EQUAL,LESS_EQUAL,
    GREATER_THAN, LESS_THAN, GREATER_EQUAL_THAN, LESS_EQUAL_THAN,
    PLUS, MINUS,
    MUL, DIV, MOD,
    AND, OR,
    BITWISE_AND, BITWISE_OR, BITWISE_XOR,
    LEFT_SHIFT, RIGHT_SHIFT,
    ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULT_ASSIGN, DIV_ASSIGN, MOD_ASSIGN,
    INDEXING,
}
