package main.visitor;

import java.util.ArrayList;
import java.util.List;
import main.ast.nodes.*;
import main.ast.nodes.declaration.*;
import main.ast.nodes.declarator.pointer.*;
import main.ast.nodes.expression.*;
import main.ast.nodes.declarator.*;
import main.ast.nodes.specifier.*;
import main.ast.nodes.statement.*;
import main.ast.nodes.type.*;
import main.ast.nodes.expression.initializer.*;


public interface IVisitor<T> {

    T visit(Program program);
    T visit(Declaration declaration);
    T visit(FuncDec funcDec);
    T visit(ParamDec paramDec);
    T visit(VarDec varDec);
    T visit(Declarator declarator);
    T visit(ArrayDeclarator arrayDeclarator);
    T visit(FunctionDeclarator functionDeclarator);
    T visit(IdentifierDeclarator identifierDeclarator);
    T visit(InitDeclarator initDeclarator);
    T visit(PointerDeclarator pointerDeclarator);
    T visit(StarPointer starPointer);
    T visit(Expression expression);
    T visit(ArrayExpression arrayExpression);
    T visit(BinaryExpression binaryExpression);
    T visit(CastExpression castExpression);
    T visit(CommaExpression commaExpression);
    T visit(CompoundLiteralExpression compoundLiteralExpression);
    T visit(ConditionalExpression conditionalExpression);
    T visit(ConstExpression constExpression);
    T visit(DigitSequenceExpression digitSequenceExpression);
    T visit(FunctionCallExpression functionCallExpression);
    T visit(IdExpression idExpression);
    T visit(SizeofExpression sizeofExpression);
    T visit(StringExpression stringExpression);
    T visit(UnaryExpression unaryExpression);
    T visit(Initializer initializer);
    T visit(InitializerEntry initializerEntry);
    T visit(FieldDesignator fieldDesignator);
    T visit(ArrayDesignator arrayDesignator);
    T visit(Designator designator);
    T visit(Specifier specifier);
    T visit(ConstSpecifier constSpecifier);
    T visit(TypedefSpecifier typedefSpecifier);
    T visit(Statement statement);
    T visit(BreakStatement breakStatement);
    T visit(CompoundStatement compoundStatement);
    T visit(ContinueStatement continueStatement);
    T visit(DoWhileStatement doWhileStatement);
    T visit(ExpressionStatement expressionStatement);
    T visit(ForCondStatement forCondStatement);
    T visit(ForStatement forStatement);
    T visit(IfStatement ifStatement);
    T visit(ReturnStatement returnStatement);
    T visit(WhileStatement whileStatement);
    T visit(Type type);
    T visit(BoolType boolType);
    T visit(CharType charType);
    T visit(DoubleType doubleType);
    T visit(FloatType floatType);
    T visit(IdType idType);
    T visit(IntType intType);
    T visit(LongType longType);
    T visit(ShortType shortType);
    T visit(SignedType signedType);
    T visit(UnsignedType unsignedType);
    T visit(VoidType voidType);
}
